name: CI Workflow with MLflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CSV_TRAIN_URL: MLProject/penguins_train_preprocessing.csv
  CSV_TEST_URL: MLProject/penguins_test_preprocessing.csv

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up job
      run: echo "Starting CI workflow"

    - name: Run actions/checkout@v3
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    - name: Check Env
      run: |
        echo "CSV Train URL: $CSV_TRAIN_URL"
        echo "CSV Test URL: $CSV_TEST_URL"
        python --version
        pip --version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true
        pip install mlflow==2.19.0 scikit-learn==1.7.0 pandas==2.3.0 numpy==2.3.0 cloudpickle==3.1.1 psutil==5.9.0 scipy==1.15.3

    - name: Run mlflow project
      run: |
        mlflow run MLProject --env-manager=local

    - name: Get latest MLflow run_id
      id: get_run_id
      run: |
        RUN_ID=$(ls -t mlruns/0 | head -n 1)
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT

    - name: Install Python dependencies
      run: pip install requests

    - name: Upload to Github
      run: |
        mkdir -p MLProject/artifacts
        cp -r ./mlruns MLProject/artifacts/
        git config --global user.name ${{ secrets.HG_USERNAME }}
        git config --global user.email ${{ secrets.HG_EMAIL }}
        git add MLProject/artifacts/
        git commit -m "Upload MLflow artifacts from CI run ${{ github.run_number }}" || echo "No changes to commit"
        git push origin main

    - name: Build Docker Model with MLflow
      run: |
        mlflow models build-docker \
          -m mlruns/0/${{ steps.get_run_id.outputs.run_id }}/artifacts/model \
          -n ${{ secrets.DOCKER_USERNAME }}/mlflow-penguins:${{ github.run_number }}

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Docker Image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/mlflow-penguins:${{ github.run_number }} ${{ secrets.DOCKER_USERNAME }}/mlflow-penguins:latest

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-penguins:${{ github.run_number }}
        docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-penguins:latest

    - name: Post Log in to Docker Hub
      run: echo "Docker image pushed successfully."

    - name: Post Set up Python 3.12.7
      run: echo "Python setup complete."

    - name: Post Run actions/checkout@v3
      run: echo "Repo checkout complete."

    - name: Complete job
      run: echo "Workflow CI complete!"
